config/routes.rb
Rails.application.routes.draw do
  resources :locations
  root 'wishes#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :wishes do
    member do
      put "like", to: "wishes#upvote"
      put "dislike", to: "wishes#downvote"
    end
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :wish
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :wish
  geocoded_by :address
  validates :address, presence: true
  after_validation :geocode, if: ->(obj){ obj.address.present? and
                                               obj.address_changed? and
                                               obj.latitude.nil? }
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :wish
  belongs_to :user
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  has_and_belongs_to_many :wishes
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :wishes
  has_and_belongs_to_many :skills
  has_and_belongs_to_many :tools
  acts_as_voter

  attr_accessor :login

  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }

    validate :validate_username

    def validate_username
      if User.where(email: username).exists?
        errors.add(:username, :invalid)
      end
    end

    def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        conditions[:email].downcase! if conditions[:email]
        where(conditions.to_hash).first
      end
    end
end

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
  has_one :location, dependent: :destroy
  has_many :images, dependent: :destroy
  has_and_belongs_to_many :skills
  has_and_belongs_to_many :tools
  accepts_nested_attributes_for :location
  accepts_nested_attributes_for :skills
  accepts_nested_attributes_for :tools
  validates :title, :description, presence: true

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :upvote, :downvote]

  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.order(cached_votes_score: :desc).page params[:page]
    @location = request.location
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
  end

  # GET /wishes/new
  def new
    @wish = Wish.new
    @wish.build_location
    @wish.skills.new
    @wish.tools.new
  end

  # GET /wishes/1/edit
  def edit
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = current_user.wishes.new(wish_params)

    respond_to do |format|
      if @wish.save

        if params[:photos]
          params[:photos].each do |photo|
            @wish.images.create(photo: photo)
          end
        end

        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render :show, status: :created, location: @wish }
      else
        format.html { render :new }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishes/1
  # PATCH/PUT /wishes/1.json
  def update
    respond_to do |format|
      if @wish.update(wish_params)
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { render :show, status: :ok, location: @wish }
      else
        format.html { render :edit }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish.destroy
    respond_to do |format|
      format.html { redirect_to wishes_url, notice: 'Wish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @wish = Wish.find(params[:id])
    @wish.upvote_by current_user
    redirect_to wishes_path
  end

  def downvote
    @wish = Wish.find(params[:id])
    @wish.downvote_by current_user
    redirect_to wishes_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_wish
    @wish = Wish.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wish_params
    params.require(:wish).permit(:title, :description, location_attributes: [:address], skills_attributes: [:name], tools_attributes: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/_alert.html.erb
<div class="alert 
    <%= 
    case type.to_sym 
    when :alert, :danger, :error, :validation_errors
        'alert-danger'
    when :warning, :todo
        'alert-warning'
    when :notice, :success
        'alert-success'
    else 
        'alert-info'
    end
    %>
     alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= content %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to image_tag("logo.png", size: "20"), root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->

  <ul class="nav navbar-nav">
    <li>
      <%= link_to 'New Wish', new_wish_path %>
    </li>
  </ul>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png"), root_path, class: "navbar-left navbar-logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'New Wish', new_wish_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wellwish</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='https://fonts.googleapis.com/css?family=Noto+Serif' rel='stylesheet' type='text/css'>   <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/navbar" %>

    <div class="container">
      <div class="row">
        <% flash.each do |type, content| %>
          <% if content.respond_to?('each') %>
            <% content.each do |item| %>
              <%= render 'layouts/alert', type: type, content: item %>
            <% end %>
          <% else %>
            <%= render 'layouts/alert', type: type, content: content %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Wish ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.wish %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/wishes/_form.html.erb
<%= form_for @wish, :html => { multipart: true } do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
        <% @wish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <%= f.fields_for :location do |location_fields| %>
    <div class="field">
      <%= location_fields.label :address %><br>
      <%= location_fields.text_area :address %>
    </div>
  <% end %>

  <%= f.fields_for :skills do |skills_fields| %>
    <div class="field">
      <%= skills_fields.label "Skill" %><br>
      <%= skills_fields.text_field :name %>
    </div>
  <% end %>

  <%= f.fields_for :tools do |tools_fields| %>
    <div class="field">
      <%= tools_fields.label "Tool" %><br>
      <%= tools_fields.text_field :name %>
    </div>
  <% end %>

  <%= f.label :images %>
  <%= file_field_tag "photos[]", type: :file, multiple: true %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishes/_wish.html.erb
<div class="media">
  <div class="media-left">
    <% if wish.images.exists? %>
      <%= image_tag wish.images.first.photo.url(:thumb), class: "media-object" %>
    <% end %>
    <div class="text-center">
      <%= link_to(like_wish_path(wish), { method: :put }) do %>
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
      <% end %>
      <%= wish.score %>
      <%= link_to(dislike_wish_path(wish), { method: :put }) do %>
        <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
      <% end %>
    </div>
  </div>

  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to wish.title, wish %>
      <% if current_user == wish.user %>
        <small>
          <%= link_to edit_wish_path(wish) do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
          <%= link_to wish, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </small>
      <% end %>
    </h4>
    <% if wish.tools.first.name.present? %>
      <span class="glyphicon glyphicon-wrench"></span>
      <% wish.tools.each do |tool| %>
        <span class="label label-default"><%= tool.name %></span>
      <% end %>
    <% end %>
    <% if wish.skills.first.name.present? %>
      <span class="glyphicon glyphicon-education"></span>
      <% wish.skills.each do |skill| %>
        <span class="label label-default"><%= skill.name %></span>
      <% end %>
    <% end %>
    <p><%= wish.description %></p>
    <p>
      submitted <%= time_ago_in_words(wish.created_at) %> ago by <%= link_to wish.user.username, "#" %>
    <% if wish.location.latitude.present? and wish.location.longitude.present? %>
      around <%= number_to_human(1000 * wish.location.distance_to([@location.latitude,@location.longitude]), units: :distance, precision: 2, delimiter: ",") %> away
    <% end %>
    </p>
  </div>
</div>

app/views/wishes/edit.html.erb
<h1>Editing Wish</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<h1>Wishing Well</h1>
<%= paginate @wishes %>
<%= render @wishes %>
<%= paginate @wishes %>

app/views/wishes/new.html.erb
<h1>New Wish</h1>

<%= render 'form' %>

<%= link_to 'Back', wishes_path %>

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Title:</strong>
<%= @wish.title %>
</p>

<p>
<strong>Description:</strong>
<%= @wish.description %>
</p>

<p>
<strong>Address:</strong>
<%= @wish.location.address %>
</p>

<p>
<strong>Latitude:</strong>
<%= @wish.location.latitude %>
</p>

<p>
<strong>Longitude:</strong>
<%= @wish.location.longitude %>
</p>

<p>
<strong>Skills:</strong>
<% @wish.skills.each do |skill| %>
  <%= skill.name %>
<% end %>
</p>

<p>
<strong>Tools:</strong>
<% @wish.tools.each do |tool| %>
  <%= tool.name %>
<% end %>
</p>

<p>
<strong>Pictures:</strong>
</p>
<% @wish.images.each do |image| %>
  <p><%= link_to image_tag(image.photo.url(:medium)), image.photo.url %></p>
<% end %>

<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'Back', wishes_path %>